#!/bin/bash
#SBATCH --partition=debug
#SBATCH --ntasks=15
#SBATCH --cpus-per-task=8
#SBATCH --distribution=block:block

#Step 1: Create a corrected functional image file from the raw data file 

#1.1 - inputs paths/files
subject=/scratch/a/arisvoin/nakuah/POND/func.conn.analysis/bold.dtseries.output/QCedSubjects.csv
func_base="ses-01_task-rest_bold"
archive_pipedir=/scratch/a/arisvoin/desmith/pond/pipelines/fmriprep/out
outdir=/scratch/a/arisvoin/nakuah/POND/func.conn.analysis/bold.dtseries.output/ciftify_clean_img
sing_home=/scratch/a/arisvoin/nakuah/POND
ciftify_container=/scratch/a/arisvoin/mjoseph/containers/FMRIPREP_CIFTIFY/tigrlab_fmriprep_ciftify_1.3.2-2.3.2-2019-06-07-ba20178606c2.simg

#These are the parameters for the cleaning of the raw data 
#   "--detrend": true,
#   "--standardize": true,
#   "--cf-cols": "X,Y,Z,RotX,RotY,RotZ,CSF,WhiteMatter,GlobalSignal",
#   "--cf-sq-cols": "X,Y,Z,RotX,RotY,RotZ,CSF,WhiteMatter,GlobalSignal",
#   "--cf-td-cols": "X,Y,Z,RotX,RotY,RotZ,CSF,WhiteMatter,GlobalSignal",
#   "--cf-sqtd-cols": "X,Y,Z,RotX,RotY,RotZ,CSF,WhiteMatter,GlobalSignal",
#   "--low-pass": 0.009,
#   "--high-pass": 0.08,
#   "--drop-dummy-TRs": 3,
#   "--smooth-fwhm": 8


#1.2. Run the cleaning to obtain a desc-clean-bold-dtseries.nii

#results in slurm calling each subject individually for each part of the analysis
#index() {
   #head -n $SLURM_ARRAY_TASK_ID $subject \
   #| tail -n 1
#}

subs=`cat $subject`

myvar=${archive_pipedir}/ciftify/${subs}/MNINonLinear/Results/ses-01_task-rest_bold/ses-01_task-rest_bold_Atlas_s0.dtseries.nii

module load singularity/2.5.2


ciftify_clean_img() {
      #mkdir -p ${outdir}/ciftify_clean_img/${subs}
      singularity exec \
      -H ${sing_home} \
      -B ${outdir}:/output \
      -B ${archive_pipedir}:/archiveout \
      ${ciftify_container} ciftify_clean_img \
          --output-file=/output/${sub}/${sub}_${func_base}_clean_bold.dtseries.nii \
          --clean-config=/output/ciftify_clean/24MP_8Phys_4GSR.json \
          --confounds-tsv=/archiveout/fmriprep/${sub}/ses-01/func/${sub}_${func_base}_confounds.tsv \
          --left-surface=/archiveout/ciftify/${sub}/MNINonLinear/fsaverage_LR32k/${sub}.L.midthickness.32k_fs_LR.surf.gii \
          --right-surface=/archiveout/ciftify/${sub}/MNINonLinear/fsaverage_LR32k/${sub}.R.midthickness.32k_fs_LR.surf.gii \
          /archiveout/ciftify/${sub}/MNINonLinear/Results/${func_base}/${func_base}_Atlas_s0.dtseries.nii
}

for sub in $subs
do

ciftify_clean_img

echo "Cleaning the rsfMRI data" 
done
