#!/bin/bash

#partition=debug
#SBATCH --nodes=1
#SBATCH --cpus-per-task=40
#SBATCH --distribution=block:block


#This script will prepare the structural data for analysis in PALM 

#Step 1: load necessary modules

#module load mcr/R2018a
#module load palm/alpha102
#module load connectome-workbench
#module load freesurfer/6.0.0


#Step 2: Setting main variables/paths
dir=/scratch/a/arisvoin/nakuah/POND/Structural_PALM_Analysis_Rerun/CorticalThickness_EB_Age
maindir=/scratch/a/arisvoin/nakuah/POND/Structural_PALM_Analysis_Rerun
sublist=/scratch/a/arisvoin/nakuah/POND/Structural_PALM_Analysis_Rerun/subs_list.csv
SUBJECT_FILES=/scratch/a/arisvoin/desmith/pond/pipelines/fmriprep/out/ciftify
design_matrix1=/scratch/a/arisvoin/nakuah/POND/Structural_PALM_Analysis_Rerun/CorticalThickness_EB/DesignMatrix.csv
contrast_matrix1=/scratch/a/arisvoin/nakuah/POND/Structural_PALM_Analysis_Rerun/CorticalThickness_EB/ContrastMatrix.csv
infile=allsubs_merged.dscalar.nii
fname=allsubs_merged

subjects=`cat $sublist`


#Step 3: Cortical Thickness GIFTI files

exampleSubid=$(head -n 1 ${sublist})
L_CT=${SUBJECT_FILES}/${exampleSubid}/MNINonLinear/fsaverage_LR32k/*L.midthickness.32k_fs_LR.surf.gii
R_CT=${SUBJECT_FILES}/${exampleSubid}/MNINonLinear/fsaverage_LR32k/*R.midthickness.32k_fs_LR.surf.gii


#Step 4: Merge smoothed dscalar files are all participants 
args=""
while read newsub
do
    args="${args} -cifti ${maindir}/CiftifySmoothingOutputs/${newsub}.thickness.32k_fs_LR.S12.dscalar.nii"
done < ${sublist} 
echo $args


#Step 4a: this merges the cifti files and is what PALM uses
wb_command -cifti-merge ${infile} ${args}


#Step 4b: Converts the CIFTI files to GIFTI files
wb_command -cifti-separate $infile COLUMN -metric CORTEX_LEFT ${fname}_L.func.gii -metric CORTEX_RIGHT ${fname}_R.func.gii
wb_command -gifti-convert BASE64_BINARY ${fname}_L.func.gii ${fname}_L.func.gii
wb_command -gifti-convert BASE64_BINARY ${fname}_R.func.gii ${fname}_R.func.gii



#Step 5: Creating a va.shape.gii file

for sub in $subjects
  do
wb_command -surface-vertex-areas ${SUBJECT_FILES}/${sub}/MNINonLinear/fsaverage_LR32k/${sub}.L.midthickness.32k_fs_LR.surf.gii \
${dir}/tmp/${sub}_L_midthick_va.shape.gii

wb_command -surface-vertex-areas ${SUBJECT_FILES}/${sub}/MNINonLinear/fsaverage_LR32k/${sub}.R.midthickness.32k_fs_LR.surf.gii \
${dir}/tmp/${sub}_R_midthick_va.shape.gii
done



#Step 6.1.a: Calculate mean surface - Left hemisphere
MERGELIST=""
while read sub; do
  MERGELIST="${MERGELIST} -metric ${maindir}/tmp/${sub}_L_midthick_va.shape.gii";
done < ${sublist}


#Step 6.1.b: Creating a func file from the shape file. 
wb_command -metric-merge L_midthick_va.func.gii ${MERGELIST}
wb_command -metric-reduce L_midthick_va.func.gii MEAN L_area.func.gii

#Step 6.2.a: Calculate mean surface - Right hemisphere
MERGELIST=""
while read sub; do
  MERGELIST="${R_MERGELIST} -metric $maindir/tmp/${sub}_R_midthick_va.shape.gii";
done < ${sublist}

#Step 6.2.b: Creating a func file from the shape file. wb_command will automatically save results in the current dir, which is output_dir
wb_command -metric-merge R_midthick_va.func.gii ${MERGELIST}
wb_command -metric-reduce R_midthick_va.func.gii MEAN R_area.func.gii
