#!/bin/bash 


#This script will extract FA and MD measures from the Slicer Atlas that is applied to all subjects

#Step 1: load necessary modules
module load slicer/0,nightly SGE-extras/1.0


#Step 2: specify the variables for a single subject 
subjects=/projects/hnakua/DWI_QC_Protocol/AllPassed_DWI.csv

sub="`cat ${subjects}`"


path_to_created_atlas=${1}   #path to the modified mrml file 
heirarchy_file=${2}          #txt file with the heirarchies created
output_dir=${3}              #path to specified output directory


#left hemisphere 
extract1() {
/opt/quarantine/slicer/nightly/build/lib/Slicer-4.9/cli-modules/FiberTractMeasurements \
       --outputfile ${output_dir}/${sub}.txt \  #can specify the name of the text file here
       --inputdirectory \ #path to input directory where the applied atlas clusters are located
       --fiberHierarchy \ #path to the mrml cluster file and linking it to the heirarchy node 
       --inputtype Fibers_Hierarchy \
       --separator Comma 
}


#right hemisphere 
extract2() {
/opt/quarantine/slicer/nightly/build/lib/Slicer-4.9/cli-modules/FiberTractMeasurements \
       --outputfile ${output_dir}/${sub}.txt \
       --inputdirectory \
       --fiberHierarchy \
       --inputtype Fibers_Hierarchy \
       --separator Comma 
}


##still need to do all of cingulum + full_UF


while read sub; do
echo "$sub"
extract1
echo "done"
done

while read sub; do
echo "$sub"
extract2
echo "done"
done 


###this is to find the node identifying number to then run Slicer on 
grep -i \
Full_UF /projects/hnakua/Slicer/Registration_Output/clustered_atlas/iteration_00002/initial_clusters/clustered_tracts_display_100_percent.modified.mrml | cut -d ' ' -f 3
